# SonarQube project configuration
sonar.projectKey=ecommerce-dev-hub-project
sonar.projectName=ecommerce-dev-hub-project
sonar.projectVersion=1.0

# Source code information
sonar.sources=.


sonar.branch.name=dev

# SonarQube server URL and authentication token
sonar.host.url=http://sonarqube:9000
